
export default `{
    {
        "input_path": "public/index.html",
        "output_path": "qrcode/img.png",
        "minify_config": {
            "minify_code": true,
            "minify_options": {
                "includeAutoGeneratedTags": true,
                "removeAttributeQuotes": true,
                "removeComments": true,
                "removeRedundantAttributes": true,
                "removeScriptTypeAttributes": true,
                "removeStyleLinkTypeAttributes": true,
                "sortClassName": true,
                "useShortDoctype": true,
                "collapseWhitespace": true
            }
        }
    }
}`;